repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint src/
        language: system
        pass_filenames: false

      - id: ruff-check
        name: ruff check
        entry: ruff check --fix server/
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff-format
        name: ruff format
        entry: ruff format server/
        language: system
        types: [python]
        pass_filenames: false
